import io
import csv
import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from typing import List, Dict, Any

def generate_csv_report(data: List[Dict[str, Any]]) -> bytes:
    """
    Generates formatted CSV file bytes from list of dictionary records.
    """
    output = io.StringIO()
    if not data:
        return output.getvalue().encode("utf-8")

    writer = csv.DictWriter(output, fieldnames=data[0].keys())
    writer.writeheader()
    writer.writerows(data)
    return output.getvalue().encode("utf-8")

def generate_excel_report(data: List[Dict[str, Any]], title: str = "InsightIQ Executive Report") -> bytes:
    """
    Generates a stylized Excel workbook using OpenPyXL with custom headers, font styles, and auto-column width.
    """
    wb = Workbook()
    ws = wb.active
    ws.title = "Analytics Report"

    # Title Block
    ws.merge_cells("A1:E1")
    title_cell = ws["A1"]
    title_cell.value = f"INSIGHTIQ — {title.upper()}"
    title_cell.font = Font(name="Calibri", size=16, bold=True, color="FFFFFF")
    title_cell.fill = PatternFill(start_color="1E293B", end_color="1E293B", fill_type="solid")
    title_cell.alignment = Alignment(horizontal="center", vertical="center")

    if not data:
        output = io.BytesIO()
        wb.save(output)
        return output.getvalue()

    headers = list(data[0].keys())
    
    # Header Row
    for col_num, header_title in enumerate(headers, 1):
        cell = ws.cell(row=3, column=col_num)
        cell.value = str(header_title).replace("_", " ").title()
        cell.font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
        cell.fill = PatternFill(start_color="3B82F6", end_color="3B82F6", fill_type="solid")
        cell.alignment = Alignment(horizontal="center", vertical="center")

    # Data Rows
    thin_border = Border(
        left=Side(style='thin', color='E2E8F0'),
        right=Side(style='thin', color='E2E8F0'),
        top=Side(style='thin', color='E2E8F0'),
        bottom=Side(style='thin', color='E2E8F0')
    )

    for row_idx, row_data in enumerate(data, 4):
        for col_idx, key in enumerate(headers, 1):
            cell = ws.cell(row=row_idx, column=col_idx)
            val = row_data.get(key, "")
            cell.value = val
            cell.border = thin_border
            cell.font = Font(name="Calibri", size=10)
            if isinstance(val, (int, float)):
                cell.alignment = Alignment(horizontal="right")
            else:
                cell.alignment = Alignment(horizontal="left")

    # Auto adjust column widths
    for col in ws.columns:
        max_len = max(len(str(cell.value or '')) for cell in col)
        col_letter = col[0].column_letter
        ws.column_dimensions[col_letter].width = max(max_len + 4, 14)

    output = io.BytesIO()
    wb.save(output)
    return output.getvalue()

def generate_pdf_report(data: List[Dict[str, Any]], title: str = "Executive Analytics Summary") -> bytes:
    """
    Generates a PDF document using ReportLab with tables, headers, and metadata.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    story = []

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=20,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=12
    )
    subtitle_style = ParagraphStyle(
        'SubtitleStyle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor("#64748B"),
        spaceAfter=20
    )

    story.append(Paragraph(f"<b>INSIGHTIQ</b> - {title}", title_style))
    story.append(Paragraph("Generated by InsightIQ Enterprise Intelligence Engine • Confidential", subtitle_style))
    story.append(Spacer(1, 10))

    if data:
        headers = list(data[0].keys())
        table_data = [[h.replace("_", " ").title() for h in headers]]
        
        for row in data[:30]:  # Limit top rows for clean PDF formatting
            table_data.append([str(row.get(h, "")) for h in headers])

        t = Table(table_data)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1E293B")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor("#F8FAFC")),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
        ]))
        story.append(t)

    doc.build(story)
    return buffer.getvalue()
